### ISSUE TITLE
support@communitytable.market bounces back

### ISSUE THREAD

**Issue by loretta-t** [community-table-market/addison-county#10]
**What happens**
Email to "support@communitytable.market" bounced back

**What you expected to happen**
From README documentation: "When you initially create an account, you will not have permission to create a business. We will be enabling "request permission to create a business" functionality very shortly, but in the meantime: just email support@communitytable.market and we'll enable business-creation permissions for your account."

**Screenshots**
You can drag and drop images here.
<img width="794" alt="Screen Shot 2020-08-23 at 10 52 34 PM" src="https://user-images.githubusercontent.com/21224411/90998985-5d826000-e593-11ea-9205-0d9500f0443a.png">

**Comment by wkelley11** [comment]
Thanks for pointing this out!  We have updated the "support@communitytable.market" account so that it can receive emails and direct them a team member to hand the issue.

**Comment by justindoran** [comment]
This was my bad.
