### ISSUE TITLE
Help us create a way for orders to be customized

### ISSUE THREAD

**Issue by wkelley11** [community-table-market/addison-county#14]
Should a user be able to make modifications to a standard order item?  What would that look like?  What does this mean for menus that rely on some degree of customization?
> Adding a protein a dish from a list of options
> How well done to you'd like your meat
> What "level" of spice you'd like
> No cheese 

Right now, our menus only allow people to order what a business has listed, but we would like to provide greater flexibility.  Let us know what that could look like!

**Comment by loretta-t** [comment]
Some ideas on this topic were addressed in the Google doc as part of #27 (ref page 7 of ther Google doc)-- we can expand on this as needed

**Comment by justindoran** [comment]
This was handled in a recent feature push through the special instructions menu.
