### ISSUE TITLE
can't edit the restaurant I made

### ISSUE THREAD

**Issue by roymichaeldonald** [community-table-market/addison-county#26]
I created a restaurant, a menu, and added an item to the menu, but now I can't find a way to go back and edit that. Seems like a space where it is clear to see a list of restaurants, menus, and items and easy way to quickly edit would be good.

**Comment by justindoran** [comment]
Yeah, it's possible to get back to it, but it's very unclear. This is why #27 is such a good idea, and should clear up this lack of clarity when it's done.
